# Generated by Django 5.2.5 on 2025-11-27 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frota', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='prefixo',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
